### ISSUE TITLE
Write(interact) with AavegotchiGameFacet results in error.

### ISSUE THREAD

**Issue by HankHoneymoon** [mark3labs/louper-v2#1]
Issue: Using Chrome, Brave, and/or Firefox (both in private window and normal window), at https://louper-mark3labs-pro.vercel.app/ and logging in with Metamask on Polygon Mainnet with private Polygon Mainnet Infura RPC, I am copy-pasting the array from read: AavegotchiFacet(tokenIdsOfOwner) to write: AavegotchiGameFacet(interact) but receiving "invalid value for an array" as an error message. 

Format from tokenIdsOfOwner: "[   5601,   9302,   3682,   1987,   7880,   4319,   19481,   11677 ]"

Tried the same at Louper.dev. Returns an infinite pulsating gemstone emoji.

I was able to complete write to AavegotchiFacet(setPetOperatorForAll) and set to true and to verify with read.

**Comment by ezynda3** [comment]
The version hosted at this URL is deprecated and will no longer be maintained.
