### ISSUE TITLE
Payable functions have no way send anything

### ISSUE THREAD

**Issue by jhubbardsf** [mark3labs/louper-v2#104]
On etherscan, if a function is marked `payable` then you generally get an "amount in ether" field along with the other arg fields that you can submit. This allows you to write to a payable function. I noticed we don't have that in louper. Is there a reason for that or has it just not been added yet? If not, I'd be happy to take a crack at adding it.

**Comment by ezynda3** [comment]
Hi. Sorry for the late reply. Yeah this is something that was just overlooked on my part. You're more than welcome to submit a PR for this. Would be awesome!

**Comment by ezynda3** [comment]
Fixed in PR #121
