### ISSUE TITLE
[Bug]: bool inputs in functions

### ISSUE THREAD

**Issue by Walodja1987** [mark3labs/louper-v2#149]
Is it possible that the bool check box for function arguments doesn't work properly? I left the box unchecked (see screenshot below) assuming that it will pass `false` as argument, but it seems like it passed `true` instead. I tested it via one of my scripts to exclude that it's an issue with the smart contract. 

Here the corresponding transaction: https://polygonscan.com/tx/0xa93a2de6e16ffd67f9441d553aa2781e1488f879ac8f6b4c2a75d908bfa38545

Here the function call via louper.dev:
![image](https://user-images.githubusercontent.com/37043174/220595928-76b393df-ea84-49cf-9931-b1b3beae551b.png)

Here the list of parameters that was passed when I triggered that function call.
![image](https://user-images.githubusercontent.com/37043174/220596712-7e960aab-eeac-4026-aa72-1de81e9d90e1.png)

I tested the same function with the box checked and it also used `true`. Looks like the boolean is hard-coded to true somehow.

**Comment by jewelsonn** [comment]
I agree with this, the bool doesn't work. The work around is to modify the html page source and add _value="true/false"_ . 

I suggest a dropdown menu to select condition instead of a checkbox.

**Comment by ezynda3** [comment]
Fixed in #163
