### ISSUE TITLE
[Bug] Returning IERC20 as Address 

### ISSUE THREAD

**Issue by jewelsonn** [mark3labs/louper-v2#159]
I have a _onlyOwner_ function triggered by admint that returns an Address or IERC20 (Which is address but in type of IERC20) .
The same function correctly works else where, like in Remix Ethereum EVM, hardhat, Testnet, etc, except for it won't work on Loupers.dev

**Chrome Error Log:**
[louper.dev-1682078301819.log](https://github.com/mark3labs/louper-v2/files/11295479/louper.dev-1682078301819.log)

**Comment by ezynda3** [comment]
What is the address and chain of the diamond?
