### ISSUE TITLE
how to input data of type uint256[] array into input field?

### ISSUE THREAD

**Issue by junhuang-ho** [mark3labs/louper-v2#2]
what is the correct way to input an array of type `uint256[]` into the input field in louper.dev?

I typed `[2000000000000,3000000000000,4000000000000,5000000000000,6000000000000,7000000000000]` in the input field and got this error:

> invalid value for array (argument="value", value="[2000000000000,3000000000000,4000000000000,5000000000000,6000000000000,7000000000000]", code=INVALID_ARGUMENT, version=contracts/5.5.0)

**Comment by ezynda3** [comment]
This should be fixed with PR #31
