### ISSUE TITLE
passing tuple as input parameter

### ISSUE THREAD

**Issue by failfmi** [mark3labs/louper-v2#23]
Hello,
is it possible to pass a `tuple` as input to a function? Example is Aavegotchi's `diamondCut` functionality.
![image](https://user-images.githubusercontent.com/20928965/156216701-9f340c3a-ebae-4e08-a3d1-510bbd567b5a.png)

Thanks!

**Comment by ezynda3** [comment]
This is a subplicate of #2 
Will fix once I get some time. PRs are also welcome :)
