### ISSUE TITLE
Louper is showing UNVERIFIED, but the contract is verified

### ISSUE THREAD

**Issue by clintonm9** [mark3labs/louper-v2#29]
https://louper.dev/diamond/0x587912a3112dde6bd20b8f6c27174e5a5516c97f?network=fuji
Last facet on the page.

https://testnet.snowtrace.io/address/0x1505c5E9CA72e7A07611cee7AA16Fd20Ecc08036#writeContract

**Comment by ezynda3** [comment]
I've investigated the issue and it seems to be on Snowtrace's end. When querying the details for your contract it doesn't return any ABI as it should. This is what is actually returned.

```
{"status":"0","message":"NOTOK","result":[{"SourceCode":"","ABI":"","ContractName":"","CompilerVersion":"","OptimizationUsed":"0","Runs":"0","ConstructorArguments":"","Library":"","SwarmSource":""}]}
```

I have no control over this unfortunately. In the mean time I can suggest trying to verify using https://sourcify.dev/. Louper recently added support for this.
