### ISSUE TITLE
when i hit execute button no transaction pops up 

### ISSUE THREAD

**Issue by NoWeiBruh** [mark3labs/louper-v2#3]
Hi i press the execute button on Aavegotchi Faucet (this is on polygon) & no transaction pops up. help please sers 💜 

![unknown](https://user-images.githubusercontent.com/88006838/148788295-3333a0c2-e42c-4042-b280-1428f4ef50b8.png)

**Comment by ezynda3** [comment]
Working on this but haven't been able to track down the underlying issue yet.
