### ISSUE TITLE
Write function call not working.

### ISSUE THREAD

**Issue by GVTopCoder** [mark3labs/louper-v2#39]
I put this on onclickdapp and the function executed fine with the combined ABI, so not sure why it fails on Louper

![](https://cdn.discordapp.com/attachments/951483625092816976/957413338877411378/Screen_Shot_2022-03-26_at_3.56.13_PM.png) Seem to be having a problem with calling this write function setURI, there are two of them, wondering if that has something to do with it.

[https://louper.dev/diamond/0x127E47abA094a9a87D084a3a93732909Ff031419?network=mumbai](https://louper.dev/diamond/0x127E47abA094a9a87D084a3a93732909Ff031419?network=mumbai)

**Comment by ezynda3** [comment]
Looks like it's not handling methods that share the same name but different signature correctly. Will look into it.

**Comment by ezynda3** [comment]
Fixed

**Comment by failfmi** [comment]
Hey, is it redeployed?
