### ISSUE TITLE
Issues with the _revenueSplit field in the addGotchiLending function of the Aavegotchi Diamond Smart Contract

### ISSUE THREAD

**Issue by nofuturistic** [mark3labs/louper-v2#52]
Hello. To start off, I'd like to say I am very new to dev stuff so I will try my best to explain the issue I've found.

 Recently, I have tried using louper.dev to interact with the Aavegotchi Diamond Smart Contract. Specifically, I attempted to use the addGotchiLending function (Gotchi Lending Facet) of the smart contract but continue to run into an issue with the revenueSplit field.  I've tried changing the formatting of how I enter the values into this field and get the same error. I attempted to get further guidance from the dev chat in the Aavegotchi discord and every suggestion has failed. The main feedback I received is that it is a potential UI issue for louper.dev but I have no idea lol

Any help would be greatly appreciated

NoFuturistic

<img width="626" alt="Screen Shot 2022-06-01 at 4 21 36 PM" src="https://user-images.githubusercontent.com/106707780/171504055-6d52d42d-46ff-4178-8edb-0db668cfede3.png">
<img width="656" alt="Screen Shot 2022-05-31 at 5 47 48 PM" src="https://user-images.githubusercontent.com/106707780/171504072-54b5dfcb-c0ce-456c-bd54-f4f5322c3f79.png">

**Comment by ezynda3** [comment]
Fixed by #53
