### ISSUE TITLE
Showing all functions of a facet instead of only the functions that are in use

### ISSUE THREAD

**Issue by Rotemy** [mark3labs/louper-v2#78]
https://louper.dev/diamond/0x5b0b687c40c3274272535bDe7F5D19861Fd9E23e?network=mainnet

2 TheCollectorsNFTVaultTokenManagerFacet with all functions, although in the second one only one function is used 
[L](https://louper.dev/diamond/0x5b0b687c40c3274272535bDe7F5D19861Fd9E23e?network=mainnet)

Love this tool

**Comment by ezynda3** [comment]
Fixed in #80
