### ISSUE TITLE
Verify facets in Binance Smart Chain Testnet (BNB testnet)

### ISSUE THREAD

**Issue by PushinSt** [mark3labs/louper-v2#97]
Hi, why do not facets initialized? They are verify already. 

> network: BNB testnet
> Diamond:
> https://louper.dev/diamond/0xff3768c33231bd9923a1138c3fb3a251da40935d?network=binance_testnet
> Example facet (number one):
> https://testnet.bscscan.com//address/0xde99bd340eb3f90feae1b18dbbd9bd4c03a976a1

ps Sentence:
Does [this (config.ts)](https://github.com/mark3labs/louper-v2/blob/9a1bff8525c0c88a56bdb6495284014673359a8d/src/lib/config.ts#L87) need to be changed **https://testnet.binance.vision/api**?

**Comment by ezynda3** [comment]
Fixed with #103
